### PR TITLE
SUM-290: hidden

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Removed `hidden` to keep Apply Now and Request info buttons from disappearing.
- The clients want the buttons to always be present according to the ticket. 

# Review By (Date)
- 11/22

# Criticality
- High

# Urgency
- High

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this gitpod
3. Navigate to a page
4. Verify the two buttons stay and don't disappear. 

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
[- SUM-290](https://stanfordits.atlassian.net/browse/SUM-290)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by rebeccahongsf — APPROVED** [review]
Huzzah! It works 🎉 Thank you, @jenbreese

**Comment by pookmish** [comment]
The production site is using the `main` branch. when a commit/merge is pushed to the `1.x` branch, there's an automated task that will update the `dev` and `test` branches. To deploy a change to production, we have to merge the `1.x` into `main` using `git checkout main && git merge 1.x`

I'm going to add a eslint rule to check for these `hidden` classes.

**Comment by pookmish** [comment]
@jenbreese it looks like there is one more use of the hidden class on the component in `src/components/layouts/interior-page.tsx`

Also it's worth mentioning that responsive classes for hidden aren't impacted. things like `lg:hidden` still work normally because the Slate uses a style like this: 
```
.hidden {display:none !important}
```
so if we use a responsive class, the class name doesn't match `.hidden` selector.

**Comment by jenbreese** [comment]
@pookmish Thank you.  I updated the `hidden` you found. It was on the skip secondary navigation link.

**Review by pookmish — APPROVED** [review]

**Pull request merged**
